/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ems_djmit;

import java.awt.Color;
import java.sql.*;
import java.text.StringCharacterIterator;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class event_data extends javax.swing.JFrame {
    JOptionPane jp;
    public int validate=0;
   // String alpha = "/^[a-zA-Z]*$/";
    /**
     * Creates new form event_data
     */
    public event_data() {
        initComponents();
        
    }
    
    private boolean validateName( String name ) { 
        
            StringCharacterIterator iterator = new StringCharacterIterator(name); 
            char character = iterator.current(); 
            while (character != StringCharacterIterator.DONE ) { 
            boolean isValidChar = (Character.isLetter(character) || Character.isSpaceChar(character) || character =='\''); 
            if (!isValidChar) { 
           // JOptionPane.showMessageDialog(null, "Names Can contain only letters, spaces and apostrophes.", "Input Error",JOptionPane.ERROR_MESSAGE); 
            validate=1;
            return true; 
        } 
            character = iterator.next(); 
        } 
            return false; 
    } 
    
    public event_data(int b) {
        initComponents();
        id.setFocusable(true);
        if(b==1)
        {
            submit.setVisible(false);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        org1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        org2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        org3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        months = new javax.swing.JComboBox();
        years = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        nop = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        toe = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        days = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        daye = new javax.swing.JComboBox();
        monthe = new javax.swing.JComboBox();
        yeare = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nos = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        disp = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event");
        setBackground(new java.awt.Color(102, 0, 51));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Event", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Title :");

        title.setColumns(30);
        title.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        title.setName("title"); // NOI18N
        title.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                titleFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Organizer 1 :");

        org1.setColumns(20);
        org1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        org1.setName("org1"); // NOI18N
        org1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                org1FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Organizer 2 :");

        org2.setColumns(20);
        org2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        org2.setName("org2"); // NOI18N
        org2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                org2FocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Organizer 3 :");

        org3.setColumns(20);
        org3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        org3.setName("org3"); // NOI18N
        org3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                org3FocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Type Of Event :");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Start Date :");

        months.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        months.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        months.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        years.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        years.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        years.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("No. of Programs :");

        nop.setColumns(10);
        nop.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        nop.setName("no_of_student");

        submit.setBackground(new java.awt.Color(255, 255, 153));
        submit.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.setLabel("Submit");
        submit.setMinimumSize(new java.awt.Dimension(88, 25));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        toe.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        toe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select event", "Cultural Event", "Technicle Event", "Non-Technicle Event" }));
        toe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Description :");

        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        days.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        days.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        days.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("End Date :");

        daye.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        daye.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        daye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        monthe.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        monthe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        yeare.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        yeare.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        yeare.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("ID :");

        id.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("No. of Students :");

        nos.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(months, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(years, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(toe, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(org3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                .addComponent(org2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(org1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(daye, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(monthe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yeare, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(org1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(org2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(org3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(toe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(months, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(years, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(daye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(nop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems_djmit/Go-back-icon.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        disp.setBackground(new java.awt.Color(44, 44, 58));
        disp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 255), null, null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(disp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Home hm=new Home(1);
        hm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        String s0=id.getText();
        String s1=title.getText();
        
        String s2=org1.getText();
        String s3=org2.getText();
        String s4=org3.getText();
        String s234=s2+","+s3+","+s4;
        String s5=toe.getSelectedItem().toString();
        String s61=days.getSelectedItem().toString();
        String s62=months.getSelectedItem().toString();
        String s63=years.getSelectedItem().toString();
        String s6=s61+"-"+s62+"-"+s63;
        String s71=daye.getSelectedItem().toString();
        String s72=monthe.getSelectedItem().toString();
        String s73=yeare.getSelectedItem().toString();
        String s7=s71+"-"+s72+"-"+s73;
        String s8=nop.getText();
        String s9=desc.getText();
        String s10=nos.getText();

        try
        {
            if(s0.equals(""))
            {
                id.setBackground(Color.gray);
              //  jp.showMessageDialog(null,"Please enter your name.");
                disp.setText("ID Field cannot be left empty");
                
            }

            else if(s1.equals("") )
            {
                title.setBackground(Color.gray);
                disp.setText("Title Field cannot be left empty");
                id.setBackground(Color.WHITE);
                
            }
            else if(s2.equals(""))
            {
                title.setBackground(Color.WHITE);
                disp.setText("Organizer 1 Field cannot be left empty");
                org1.setBackground(Color.gray);
            }
            else if(s5.equals("Select event"))
            {
                org1.setBackground(Color.WHITE);
                toe.setBackground(Color.red);
                disp.setText("Please select Type of event");
            }
            else if(s61.equals("Day") || s62.equals("Month") || s63.equals("Year"))
            {
                desc.setBackground(Color.WHITE);
                days.setBackground(Color.red);
                months.setBackground(Color.red);
                years.setBackground(Color.red);
                disp.setText("Please select Start Date properly");

            }
            else if(s71.equals("Day") || s72.equals("Month") || s73.equals("Year"))
            {
                
                daye.setBackground(Color.red);
                monthe.setBackground(Color.red);
                yeare.setBackground(Color.red);
                
                days.setBackground(Color.white);
                months.setBackground(Color.white);
                years.setBackground(Color.white);
                disp.setText("Please select End Date properly");

            }
            else if(s8.equals(""))
            {
                disp.setText("Please insert No. of programs");
                daye.setBackground(Color.white);
                monthe.setBackground(Color.white);
                yeare.setBackground(Color.white);
                nop.setBackground(Color.gray);
            }
            else if(s9.equals(""))
            {
                nop.setBackground(Color.white);
                disp.setText("Description Field cannot be left empty");
                desc.setBackground(Color.gray);
            }
            else if(s10.equals(""))
            {
                desc.setBackground(Color.white);
                disp.setText("Please insert No. of Students");
                nos.setBackground(Color.gray);
            }

            else
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/clg","root","admin");
                Statement ss=con.createStatement();
                //String querry="insert into researchpaper(title,author_one,author_two,author_three,type_of_event,proceding,month_year_published,issn_no,impact_factor)values("+"\'"+s1+"\'"+","+"\'"+s2+"\'"+","+"\'"+s3+"\'"+","+"\'"+s4+"\'"+","+"\'"+s5+"\'"+","+"\'"+s6+"\'"+","+"\'"+s7+"\'"+","+"\'"+s8+"\'"+","+"\'"+s9+"\'"+")";
                String querry="insert into evnt(ID,Title,Organizers,Type_of_event,Start_date,End_date,No_of_programs,Description,No_of_students)values('"+s0+"','"+s1+"','"+s234+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9+"','"+s10+"')";
                ss.executeUpdate(querry);
                ss.close();
                con.close();

                process pss=new process();
                pss.setVisible(true);
                setVisible(false);

            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            //System.out.println("problem Somewhere");
            disp.setText("Connection Problem,Please try after some time");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusLost
        
      /*  if((id.getText()).equals("") )
        {
            id.setBackground(Color.gray);
            disp.setText("ID Field cannot be left empty");
        }
        */
       /* if(validateName(id.getText())==true) { 
       // id.setText(""); 
            id.setBackground(Color.white);
            id.setFocusable(true); 
            id.requestFocus(); 
            disp.setText("Enter Valid ID");
       }
        else
        {
            id.setBackground(Color.white);
            title.setFocusable(true);
            title.requestFocus();
            disp.setText("");
        }*/
    }//GEN-LAST:event_idFocusLost

    private void org1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_org1FocusLost
        // TODO add your handling code here:
         if(validateName(org1.getText())==true) { 
       
            org1.setBackground(Color.white);
            org1.setFocusable(true); 
            org1.requestFocus(); 
            disp.setText("Enter Valid Organizer's name");
       }
        else
        {
            org1.setBackground(Color.white);
          // org2.setFocusable(true);
           //org2.requestFocus();
            disp.setText("");
        }
    }//GEN-LAST:event_org1FocusLost

    private void org2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_org2FocusLost
        // TODO add your handling code here:
         if(validateName(org2.getText())==true) { 
      
            org2.setBackground(Color.white);
            org2.setFocusable(true); 
            org2.requestFocus(); 
            disp.setText("Enter Valid Organizer's name");
       }
        else
        {
            org2.setBackground(Color.white);
          //  org3.setFocusable(true);
            //org3.requestFocus();
            disp.setText("");
        }
    }//GEN-LAST:event_org2FocusLost

    private void org3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_org3FocusLost
        // TODO add your handling code here:
         if(validateName(org3.getText())==true) { 
       
            org3.setBackground(Color.white);
            org3.setFocusable(true); 
            org3.requestFocus(); 
            disp.setText("Enter Valid Organizer's name");
       }
        else
        {
            org3.setBackground(Color.white);
            //toe.setFocusable(true);
            //toe.requestFocus();
            disp.setText("");
        }
    }//GEN-LAST:event_org3FocusLost

    private void titleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_titleFocusLost
        // TODO add your handling code here:
        /* if((title.getText()).equals("") )
        {
            title.setBackground(Color.gray);
            disp.setText("Title Field cannot be left empty");
        }
        */
        if(validateName(title.getText())==true) { 
       //id.setText(""); 
            title.setBackground(Color.white);
            title.setFocusable(true); 
            title.requestFocus(); 
            disp.setText("Enter Valid Title");
       }
        else
        {
            title.setBackground(Color.white);
           // org1.setFocusable(true);
           // org1.requestFocus();
           // disp.setText("");
        }
    }//GEN-LAST:event_titleFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(event_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(event_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(event_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(event_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new event_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox daye;
    private javax.swing.JComboBox days;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel disp;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox monthe;
    private javax.swing.JComboBox months;
    private javax.swing.JTextField nop;
    private javax.swing.JTextField nos;
    private javax.swing.JTextField org1;
    private javax.swing.JTextField org2;
    private javax.swing.JTextField org3;
    public javax.swing.JButton submit;
    private javax.swing.JTextField title;
    private javax.swing.JComboBox toe;
    private javax.swing.JComboBox yeare;
    private javax.swing.JComboBox years;
    // End of variables declaration//GEN-END:variables
}
