/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ems_djmit;

import static ems_djmit.Display.t1;
import java.awt.Color;
import java.sql.*;
import java.text.StringCharacterIterator;
import java.util.Vector;

/**
 *
 * @author ASUS
 */
public class Program extends javax.swing.JFrame {

     
    /**
     * Creates new form event_data
     */
    public Program() {
        initComponents();
        try {   
            
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/clg","root","admin");
		Statement ss=con.createStatement();
                //String querry="insert into researchpaper(title,author_one,author_two,author_three,type_of_event,proceding,month_year_published,issn_no,impact_factor)values("+"\'"+s1+"\'"+","+"\'"+s2+"\'"+","+"\'"+s3+"\'"+","+"\'"+s4+"\'"+","+"\'"+s5+"\'"+","+"\'"+s6+"\'"+","+"\'"+s7+"\'"+","+"\'"+s8+"\'"+","+"\'"+s9+"\'"+")";
                
                String querry="select ID from evnt";
                ResultSet rset;
                rset = ss.executeQuery(querry);
                              
            ResultSetMetaData md = rset.getMetaData();
            int columns = md.getColumnCount();
            
            while (rset.next()) {
                Vector row = new Vector(columns);

                for (int i = 1; i <= columns; i++) {
                    row.addElement(rset.getObject(i));
                }

                evntid.addItem(row);

            }

            rset.close();
            ss.close();
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println(e.getStackTrace());
        }
    }
        private boolean validateName( String name ) { 
        
            StringCharacterIterator iterator = new StringCharacterIterator(name); 
            char character = iterator.current(); 
            while (character != StringCharacterIterator.DONE ) { 
            boolean isValidChar = (Character.isLetter(character) || Character.isSpaceChar(character) || character =='\''); 
            if (!isValidChar) { 
           // JOptionPane.showMessageDialog(null, "Names Can contain only letters, spaces and apostrophes.", "Input Error",JOptionPane.ERROR_MESSAGE); 
           
            return true; 
        } 
            character = iterator.next(); 
        } 
            return false; 
    } 
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        coordinator = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        part = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        submit = new javax.swing.JButton();
        toe = new javax.swing.JComboBox();
        search = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        venue = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        start = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        end = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        evntid = new javax.swing.JComboBox();
        back = new javax.swing.JButton();
        disp = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program");
        setBackground(new java.awt.Color(24, 240, 240));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Program", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Title :");

        title.setColumns(30);
        title.setName("title"); // NOI18N
        title.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                titleFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Event ID :");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Co-ordinator :");

        coordinator.setColumns(20);
        coordinator.setName("coordinator"); // NOI18N
        coordinator.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                coordinatorFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("No. of student Participant :");

        part.setColumns(20);
        part.setName("part"); // NOI18N
        part.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                partFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Type Of Program :");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Month/year :");

        month.setForeground(new java.awt.Color(102, 0, 51));
        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        month.setName("month"); // NOI18N

        year.setForeground(new java.awt.Color(102, 0, 51));
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        year.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        year.setName("year"); // NOI18N

        submit.setForeground(new java.awt.Color(102, 0, 51));
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.setLabel("Submit");
        submit.setMinimumSize(new java.awt.Dimension(88, 25));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        toe.setForeground(new java.awt.Color(102, 0, 51));
        toe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "Cultural Event", "Technicle Event", "Non-Technicle Event" }));
        toe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toeActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Description :");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("ID :");

        id1.setColumns(20);
        id1.setName("id1"); // NOI18N
        id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id1ActionPerformed(evt);
            }
        });

        desc.setColumns(20);
        desc.setRows(5);
        desc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(desc);

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Venue :");

        venue.setColumns(20);
        venue.setName("venue"); // NOI18N
        venue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                venueFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Date :");

        start.setForeground(new java.awt.Color(102, 0, 51));
        start.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.setName("start"); // NOI18N
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Start :");

        end.setForeground(new java.awt.Color(102, 0, 51));
        end.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        end.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        end.setName("end"); // NOI18N
        end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("End :");

        evntid.setForeground(new java.awt.Color(102, 0, 51));
        evntid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select EventID" }));
        evntid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(toe, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(venue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(33, 33, 33)
                                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(search))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coordinator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(evntid, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGap(305, 305, 305)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(evntid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(coordinator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(toe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems_djmit/Go-back-icon.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        disp.setBackground(new java.awt.Color(44, 44, 58));
        disp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 255), null, null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(disp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        String mystr1=title.getText();
        String mystr2=evntid.getSelectedItem().toString();
        String mystr3=month.getSelectedItem().toString()+" "+year.getSelectedItem().toString();
        String mystr4=toe.getSelectedItem().toString();
       /// String mystr5=author2.getText();
        Displaypg dp=new Displaypg(mystr1,mystr2,mystr3,mystr4);
        dp.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_searchActionPerformed

    private void toeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
           
        String s1=id1.getText();
        String s2=evntid.getSelectedItem().toString();
        String s3=title.getText();
        String s4=coordinator.getText();
        String s5=part.getText();
        String s6=toe.getSelectedItem().toString();
        String s7=desc.getText();
        String s8=venue.getText();
        String s91=start.getSelectedItem().toString();
        String s92=end.getSelectedItem().toString();
        String s11=month.getSelectedItem().toString();
        String s12=year.getSelectedItem().toString();
        String s9=s91+"-"+s11+"-"+s12;
        String s10=s92+"-"+s11+"-"+s12;
        
        
        
        //String s9=month.getSelectedItem().toString()+" "+year.getSelectedItem().toString();
        //String s8=impact_factor.getText();

        try
        {

            if(s1.equals("") )
            {

                disp.setText("Please Add ID Field");
                id1.setBackground(Color.gray);
            }
            else if(s2.equals("Select EventID"))
            {
                id1.setBackground(Color.WHITE);
                disp.setText("Please select EventID");
                evntid.setBackground(Color.red);
            }
            else if(s3.equals(""))
            {
                evntid.setBackground(Color.WHITE);
                disp.setText("Title Field cannot be left empty");
                title.setBackground(Color.gray);
            }
            else if(s4.equals(""))
            {
                title.setBackground(Color.WHITE);
                disp.setText("Co-Ordinator Field cannot be left empty");
                coordinator.setBackground(Color.gray);
            }
            else if(s5.equals("No. of participant"))
            {
                coordinator.setBackground(Color.WHITE);
                disp.setText("Please select Type of event");
                part.setBackground(Color.gray);
            }
            else if(s6.equals("Select Type"))
            {
                part.setBackground(Color.white);
                disp.setText("Proceding Field cannot be left empty");
                toe.setBackground(Color.red);
            }
            else if(s7.equals(""))
            {
                toe.setBackground(Color.white);
                disp.setText("Proceding Field cannot be left empty");
                desc.setBackground(Color.gray);
            }
            else if(s8.equals(""))
            {
                desc.setBackground(Color.white);
                disp.setText("Proceding Field cannot be left empty");
                venue.setBackground(Color.gray);
            }
            else if(s91.equals("Day"))
            {
                venue.setBackground(Color.white);
                disp.setText("Proceding Field cannot be left empty");
                start.setBackground(Color.red);
            }
            else if(s92.equals("Day"))
            {
                start.setBackground(Color.white);
                disp.setText("Proceding Field cannot be left empty");
                end.setBackground(Color.red);
            }
            else if(s11.equals("Month") || s12.equals("Year"))
            {
                end.setBackground(Color.WHITE);
                disp.setText("Please select Month or year");
                month.setBackground(Color.red);
                year.setBackground(Color.red);

            }
            else
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/clg","root","admin");
                Statement ss=con.createStatement();
                //String querry="insert into researchpaper(title,author_one,author_two,author_three,type_of_event,proceding,month_year_published,issn_no,impact_factor)values("+"\'"+s1+"\'"+","+"\'"+s2+"\'"+","+"\'"+s3+"\'"+","+"\'"+s4+"\'"+","+"\'"+s5+"\'"+","+"\'"+s6+"\'"+","+"\'"+s7+"\'"+","+"\'"+s8+"\'"+","+"\'"+s9+"\'"+")";
                String querry="insert into pg(ID,Event_ID,Title,Co_ordinator,No_of_participants,Type_of_program,Description,Venue,Start_date,End_date)values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9+"','"+s10+"')";
                ss.executeUpdate(querry);
                ss.close();
                con.close();

                process pss=new process();
                pss.setVisible(true);
                setVisible(false);

            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            //System.out.println("problem Somewhere");
            disp.setText("Connection Problem, try after some time");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id1ActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    private void endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Home hme=new Home(1);
        hme.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void titleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_titleFocusLost
        // TODO add your handling code here:
        if(validateName(title.getText())==true) { 
       
            title.setBackground(Color.white);
            title.setFocusable(true); 
            title.requestFocus(); 
            disp.setText("Enter Valid Title");
       }
        else
        {
            title.setBackground(Color.white);
           // org2.setFocusable(true);
            //org2.requestFocus();
            disp.setText("");
        }
    }//GEN-LAST:event_titleFocusLost

    private void coordinatorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coordinatorFocusLost
        // TODO add your handling code here:
        if(validateName(coordinator.getText())==true) { 
       
            coordinator.setBackground(Color.white);
            coordinator.setFocusable(true); 
            coordinator.requestFocus(); 
            disp.setText("Enter Valid Co-ordinator name");
       }
        else
        {
            coordinator.setBackground(Color.white);
           // org2.setFocusable(true);
            //org2.requestFocus();
            disp.setText("");
        }
    }//GEN-LAST:event_coordinatorFocusLost

    private void partFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_partFocusLost
        // TODO add your handling code here:
        if(validateName(part.getText())!=true) { 
       
            part.setBackground(Color.white);
            part.setFocusable(true); 
            part.requestFocus(); 
            disp.setText("");
       }
        else
        {
            part.setBackground(Color.white);
           // org2.setFocusable(true);
            //org2.requestFocus();
            disp.setText("Enter Number of Participants");
        }
    }//GEN-LAST:event_partFocusLost

    private void venueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_venueFocusLost
        // TODO add your handling code here:
        if(validateName(venue.getText())==true) { 
       
            venue.setBackground(Color.white);
            venue.setFocusable(true); 
            venue.requestFocus(); 
            disp.setText("Enter Valid Co-ordinator name");
       }
        else
        {
            venue.setBackground(Color.white);
           // org2.setFocusable(true);
            //org2.requestFocus();
            disp.setText("");
        }
    }//GEN-LAST:event_venueFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField coordinator;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel disp;
    private javax.swing.JComboBox end;
    private javax.swing.JComboBox evntid;
    private javax.swing.JTextField id1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox month;
    private javax.swing.JTextField part;
    public javax.swing.JButton search;
    private javax.swing.JComboBox start;
    public javax.swing.JButton submit;
    private javax.swing.JTextField title;
    private javax.swing.JComboBox toe;
    private javax.swing.JTextField venue;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
